### ISSUE TITLE
File not found error when invoking prosv5 make

### ISSUE THREAD

**Issue by gnations56** [purduesigbots/pros-cli#10]
#### Expected Behavior:
The project will build
#### Actual Behavior:
make fails with file not found error. PROS is not specific as to which file is missing
#### Steps to reproduce:
run prosv5 make in a project folder
#### System information:
Operating System:  (Windows, OS X, Ubuntu)
Windows 10
PROS Version: (run `pros --version`)
pros, version 3.1.2
#### Screenshots/Output Dumps/Stack Traces
ERROR - __main__:main - [WinError 3] The system cannot find the path specified
  File "C:\Program Files\Python36\lib\subprocess.py", line 709, in __init__
  File "C:\Program Files\Python36\lib\subprocess.py", line 997, in _execute_child
FileNotFoundError: [WinError 3] The system cannot find the path specified

**Comment by gnations56** [comment]
Closing issue as this and issues installing were related to using 32-bit build on 64-bit system

**Comment by EricHallahan** [comment]
Sorry to bump the thread. I have the identical issue after installing PROS manually (i.e. Installing the GNU Toolchain and wheel). What was the solution? I am afraid that the provided solution is not entirely obvious.

**Comment by HotelCalifornia** [comment]
@EricHallahan what platform are you on? the OP's issue was related to using the incorrect Windows installer for their system.

If you're also on Windows, make sure that you've set the `PROS_TOOLCHAIN` environment variable.

**Comment by EricHallahan** [comment]
Windows 10 1809, 64-bit. What is in the `PROS_TOOLCHAIN` variable? I didn't use the installer. I assumed that adding GNU Tools to `PATH` would be enough.

EDIT: Still returns with the error when using the 64-bit installer

**Comment by jloh02** [comment]
I have a similar problem as well

#### Error
`prosv5 make`:
```
ERROR - __main__:main - [WinError 2] The system cannot find the file specified 
File "C:\Program Files\Python36\lib\subprocess.py", line 997, in _execute_child
# ReadFile will hang.
```

#### System information:
Operating System: Windows 10 64-bit operating system, x64-based processor

PROS Version: (run `pros --version`) pros, version 3.1.3

#### Additional Information
Installer used: pros-windows-3.1.3.0-64bit
Building from GUI does not seem to work - changes to program are not reflected once uploaded to robot

#### Screenshots/Output Dumps/Stack Traces
`echo %PATH%` (Shortened):
```
C:\Program Files\PROS\cli;
C:\Program Files\Python36\Scripts\;
C:\Program Files\Python36\;
C:\Users\Jonathan\.windows-build-tools\python27\;
C:\Program Files\PROS\cli;
C:\Program Files\PROS\toolchain\bin;
C:\Program Files\Python36\lib;
C:\Program Files\Git;
```

`echo %PROS_TOOLCHAIN%`:
C:\Program Files\PROS\toolchain\usr

**Comment by edjubuh** [comment]
The file subprocess would be failing to execute would be make.exe. It should exist in %PROS_TOOLCHAIN%\bin, but can you verify this?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jloh02** [comment]
Solved the issue. The toolchain in %PATH% should have been `C:\Program Files\PROS\toolchain\usr\bin` instead of `C:\Program Files\PROS\toolchain\bin`

**Comment by EricHallahan** [comment]
I forgot to mention I figured my problem out.

**Comment by HotelCalifornia** [comment]
@erichallahan care to share? 🙂

**Comment by EricHallahan** [comment]
I downloaded the installer and ran it. ;)
My original intention was not to install the PROS editor, and use VSCode instead with the CLI. The problem was that I did not know where to install the Arm Embedded Toolchain (the location within the `PROS_TOOLCHAIN` environment variable). I ran the installer again and modified the variable to the newest (i.e. unofficial non-release) build of GCC 8.2 that I had found. I overwrote the existing GCC install because I had no interest in it, but I could of course have changed `PROS_TOOLCHAIN`. (To answer my former self, the value of which is `C:\Program Files\PROS\toolchain\usr`.)

**Comment by 3038922** [comment]
> I downloaded the installer and ran it. ;)
> My original intention was not to install the PROS editor, and use VSCode instead with the CLI. The problem was that I did not know where to install the Arm Embedded Toolchain (the location within the `PROS_TOOLCHAIN` environment variable). I ran the installer again and modified the variable to the newest (i.e. unofficial non-release) build of GCC 8.2 that I had found. I overwrote the existing GCC install because I had no interest in it, but I could of course have changed `PROS_TOOLCHAIN`. (To answer my former self, the value of which is `C:\Program Files\PROS\toolchain\usr`.)

I also had problems with `prosv5 make`.

And how do you configure vscode?
this is my configure:
```
{
    "configurations": [
        {
            "name": "vex",
            "includePath": [
                "${env:PROS_TOOLCHAIN}/arm-none-eabi/include",
                "${env:PROS_TOOLCHAIN}/lib/gcc/arm-none-eabi/8.2.1/include",
                "${workspaceRoot}",
                "${workspaceRoot}/include"
            ],
            "defines": [
                "_POSIX_THREADS",
                "_UNIX98_THREAD_MUTEX_ATTRIBUTES"
            ],
            "limitSymbolsToIncludedHeaders": true,
            "databaseFilename": ""
        }
    ],
    "version": 4
}
```
![image](https://user-images.githubusercontent.com/33926386/52141279-2afed280-2690-11e9-974b-140abb820263.png)

**Comment by EricHallahan** [comment]
> And how do you configure vscode?

By running `prosv5 mu` in tasks.
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "make-upload",
            "type": "shell",
            "command": "prosv5 mu",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```
I recently thought of using Fortran for linear algebra, but I would need to build my own toolchain for that.

**Comment by HotelCalifornia** [comment]
> I recently thought of using Fortran for linear algebra, but I would need to build my own toolchain for that.

you'd need to do a little more than just that... as far as I can tell, the only supported Fortran compiler for arm requires a linux environment

**Comment by EricHallahan** [comment]
I will likely install Linux soon on my device, either as a VM or with wubi.

**Comment by HotelCalifornia** [comment]
No, that's not what I meant. I meant that the only compiler for fortran on arm is gfortran-arm-linux, which requires the target system have a linux environment. in this case, that target device be the v5
