### ISSUE TITLE
Feature Request: flag to filter make errors

### ISSUE THREAD

**Issue by seendsouza** [purduesigbots/pros-cli#103]
#### Expected Behavior:
New flag: `prosv5 make --oneline`
Essentially the equivalent of `prosv5 make | grep "error"` (that I currently use)
The purpose would be to make it easier to look at a large amount of errors when you're trying to fix your code.

#### Actual Behavior:
N/A

#### Steps to reproduce:
N/A

#### System information:
Operating System:  All

PROS Version: N/A

#### Additional Information
The `--oneline` comes from `git log --oneline` btw.

#### Screenshots/Output Dumps/Stack Traces
![image](https://user-images.githubusercontent.com/38793207/62839481-59b9bf00-bc58-11e9-98b9-c2fbf6890913.png)

**Comment by HotelCalifornia** [comment]
Since `prosv5 make` just passes everything directly to `make`, I don't really think it's the job of the CLI to handle extra flags like this.
