### ISSUE TITLE
Add File Redirect Option to Terminal

### ISSUE THREAD

**Issue by py2025** [purduesigbots/pros-cli#108]
User should be able to select the file that they want terminal output to be directed to.

**Comment by HotelCalifornia** [comment]
something like `prosv5 terminal --output filename`. I think we'd also want it to still display to the user what's going on (while copying output to the file in the background)

**Comment by 3038922** [comment]
It would be great if we could interact more conveniently with the host computer.

Personally, I'm going to start learning tensorflow in the near future.

**Comment by edjubuh** [comment]
There's already standard shell utilities like `prosv5 terminal > output.txt` or `prosv5 terminal | tee output.txt`. Why add this to PROS?

**Comment by HotelCalifornia** [comment]
Because it isn't hard to add and I feel that it improves user experience. People who already know how to use those standard shell utilities can of course continue to use them.

**Comment by lerker100** [comment]
If your using bash you can just run this `prosv5 terminal > test.txt`
