### ISSUE TITLE
Controller DC's right after download

### ISSUE THREAD

**Issue by sy1vi3** [purduesigbots/pros-cli#112]
Right after I download with PROS the controller disconnects from the brain for about 5 seconds. This happens EVERY time. It does not happen with VEXcode.

**Comment by theol0403** [comment]
This also happened to me the last time I worked with the robot via wireless downloading (April). This was on the kernel version before 3.2.0, using the current version of the CLI.

When I run wireless download, it switches to the download channel, downloads, and then completes. About 10-20 seconds later, the controller disconnects for about 5 seconds (I assume it is switching back to main channel). This is annoying when starting the program right after it finishes downloading and having the controller disconnect.

Here is the relevant conversation on the unofficial VEX discord server with multiple people chiming in with the same issue:
https://discordapp.com/channels/197777408198180864/198658294007463936/638120641408794634

**Comment by HotelCalifornia** [comment]
not clear yet that this is necessarily a bug in what we're doing, but thank you for opening an issue so we can investigate

**Comment by m888r** [comment]
summary of proposed solution:
- CLI flag to not switch off download channel on exit
- project flag to do the same thing
- cli commands to swap channels, etc.
https://github.com/purduesigbots/pros-cli/blob/d9c12776cd33ec1a7e5bed1145a407a05525b774/pros/serial/devices/vex/v5_device.py#L195-L198

discord discussion: https://discordapp.com/channels/197777408198180864/198658294007463936/640389061478973441

**Comment by HotelCalifornia** [comment]
May also want to explicitly tell upload not to switch channels when chaining commands like upload/terminal

**Comment by nathan-moore** [comment]
There is some related discussion on the vex forum [here](https://www.vexforum.com/t/controller-disconnecting-at-10-seconds/78034/6). Most notably, it was pointed out that we never set did_switch to true, so we never switch back to the pits channel.
