### ISSUE TITLE
Add Analytics

### ISSUE THREAD

**Issue by Octogonapus** [purduesigbots/pros-cli#121]
#### Overview

It would be good to have analytics to track how many PROS users there are, what templates and software versions they use, and what API features they use.

#### Frontend

The CLI will handle everything analytics needs: information gathering, reporting, etc. When a user uses the CLI to do anything and they have not yet configured analytics, they will first be asked if they want to opt-in to analytics. Their preference will be saved locally. If the user wishes to change their preference at any time, they can run `prosv5 analytics --opt-in/out` to `--opt-in` or `--opt-out`.

#### Backend

How often to report data:
- Report on upload seems adequate, though it might report unnecessarily often. How often is "too often" will depend on the backend service used.

We have considered:
- Sentry. This is currently used for error reporting. Adding analytics will not be free.
- Google Analytics. Still being discussed.

#### Information Gathering

- The number of PROS users (and their region?)
- Which templates are used (template name, version, and location)
- Per template:
  - Which (relevant) symbols are present in the latest program

**Comment by kunwarsahni01** [comment]
Analytics are now basically finished in the atom plugin. We decided to use Google Analytics for that and I think it would make the most sense to continue to use that for the cli as well. This would automatically collect the necessary user data (number of users and region). We could then setup up events for various "actions" that users take
