### ISSUE TITLE
[Request] Build a VEXCode project using prosv5

### ISSUE THREAD

**Issue by GentlyTech** [purduesigbots/pros-cli#124]
Uploading a binary to the V5 Brain without a project works great, but building a VEXCode project doesn't seem to be implemented.

**Feature Request:**
So, I was wondering if *building a VEXCode project from the pros CLI* could be a feature, as some people (like me) prefer another IDE such as Visual Studio but still want to program in VEX C++ and not PROS, and don't want to have VEXCode open alongside just to build the code.

(It looks like VEX uses makefiles, but I'm not sure how to configure it manually as running make on it doesn't work, so if someone can point me in the right direction on how to configure/use make that would work too)

Thanks!

**Comment by HotelCalifornia** [comment]
Yeah, sorry I don't think we're looking to implement or support this.
