### ISSUE TITLE
pros cli fails to find make program in Fedora

### ISSUE THREAD

**Issue by GLMONTER** [purduesigbots/pros-cli#125]
#### Expected Behavior:
Project to compile

#### Actual Behavior:
failed to compile with make error

#### Steps to reproduce:
attempt to compile project using any linux distro but Ubuntu

#### System information:
Fedora 31

PROS Version: 3.1.4

![Screenshot from 2020-02-27 13-51-59](https://user-images.githubusercontent.com/43346260/75481318-77d2dc80-5968-11ea-9daa-7b07d2ca811f.png)

**Comment by nathan-moore** [comment]
I assume this is caused by you not having make. You also might run into https://github.com/purduesigbots/pros/issues/206. Feel free to reopen if it's something else.
