### ISSUE TITLE
[prosv5]ubuntu1804 can't create" compile_commands.json" 

### ISSUE THREAD

**Issue by 3038922** [purduesigbots/pros-cli#13]
ubuntu 1804 
pyhton 3.6.6 
pip 9.0.1.

![1](https://user-images.githubusercontent.com/33926386/46590200-10eb2400-cae4-11e8-925c-98992643b4e5.png)
![2](https://user-images.githubusercontent.com/33926386/46590202-10eb2400-cae4-11e8-833f-fa7c4f73a2c8.png)
![3](https://user-images.githubusercontent.com/33926386/46590203-1183ba80-cae4-11e8-83dc-b36ddecf3b5a.png)

**Comment by HotelCalifornia** [comment]
You'll need to make sure you have https://github.com/cquery-project/cquery installed and on PATH

**Comment by 3038922** [comment]
cquery --help ,cquery --version can't be use.
how to add cquery global path to ubuntu1804?
thank you

**Comment by HotelCalifornia** [comment]
please follow the instructions provided for your platform on the linked repository

**Comment by 3038922** [comment]
ok! use bear make it can be created .
but in windows10 1809 ,i can't use bear make .
what shoud i do?

**Comment by HotelCalifornia** [comment]
If you have run the windows installer and selected the PROS Editor option, cquery will have been installed and put on PATH for you. In this case, running `prosv5 build-compile-commands` or using the editor to build will generate the compile cache for cquery.

**Comment by 3038922** [comment]
Thanks for solving all my problems. Only under WIN10 1809.CQUERY runs very unstable. I am learning recently that LITTLEVGL often encounters bugs that require RELOAD ATOM

**Comment by HotelCalifornia** [comment]
I'm glad I was able to help.

I haven't noticed any particular problems with running cquery on windows, and I'm not quite sure what you mean about LVGL. I'm going to close this issue because that seems to be a different problem.
