### ISSUE TITLE
Is it time for a new release?

### ISSUE THREAD

**Issue by Sleuth56** [purduesigbots/pros-cli#130]
It's been a year and a half sense the last release of Pros CLI. With the new release of the Pros kernel, teams starting up for this season, and all the new features that have been developed. It seems like there needs to be an update. I for one have been using my own fork with some of the fixes and feature that aren't out sense April.

**Comment by HotelCalifornia** [comment]
yes

**Comment by Sleuth56** [comment]
Has this topic been discussed internally yet? It's been 4 months and teams really need these new features heading into the heavy competition season. I'm about to make a fork and implement all the new changes my self it's been so long.

**Comment by WillXuCodes** [comment]
> Has this topic been discussed internally yet? It's been 4 months and teams really need these new features heading into the heavy competition season. I'm about to make a fork and implement all the new changes my self it's been so long.

Yes, this has been discussed internally but right now the focus is the docs (for this week). If things go well, the following week is planned to be dedicated to the CLI. That being said, if you create a PR with that fork that'd also be greatly appreciated.

**Comment by Sleuth56** [comment]
@WillXuCodes I've compiled all the open PRs to a seperate git repo. I was wondering exactly what you all are looking for in a PR? So while I'm testing and merging the PRs I can keep that in mind.

**Comment by Sleuth56** [comment]
@HotelCalifornia He asked for me to create a PR when I implement all the new changes. So I'm asking exactly how you all want that. I'm not sure if a PR with all the other PRs in one branch or what he was asking for?

**Comment by WillXuCodes** [comment]
@lerker100 I may have originally misinterpreted what you were saying, I originally thought you said you worked on new features yourself and wanted to implement them on your own fork. No need for the PR then, but do note that some others do have their own CLI builds (with wireless terminal and other unreleased features) and are doing something similar to what you are planning to do.

**Comment by kunwarsahni01** [comment]
We are working through CLI issues/PRs now.
