### ISSUE TITLE
Compilation Errors on Arch Linux

### ISSUE THREAD

**Issue by frankyaoxiao** [purduesigbots/pros-cli#133]
#### Expected Behavior:

Project to Compile
#### Actual Behavior:

Multiple "unrecognized command-line option" errors outputted

#### Steps to reproduce:

Download latest version of Arch Linux and arm-none-eabi-gcc from Arch repositories, clone existing repo from github and try to make project

#### System information:
Operating System:  
Arch Linux

PROS Version: 
Prosv5 version 3.1.4

#### Additional Information

The project was initially made on a Windows operating system by another team member, is there any discrepancies between the common.mk of Linux and Windows? I saw [this issue](https://github.com/purduesigbots/pros/issues/206) and I wonder if this is an OS issue, because that one appears to have been fixed. Additionally, I am using the gcc arm package in the Arch Linux Repository, and this [seems to have caused problems before](https://github.com/purduesigbots/pros/issues/146), but I think that these 2 errors are unrelated, so I don't think that the package is the error. 

#### Screenshots/Output Dumps/Stack Traces
prosv5 make:
Creating cold package with libc libm libpros okapilib, [ERRORS]
arm-none-eabi-g++: error: unrecognized command-line option '--whole-archive'; did you mean '--whole-file'?
arm-none-eabi-g++: error: unrecognized command-line option '--no-whole-archive,'; did you mean '--no-whole-file'?
make: *** [common.mk:227: bin/cold.package.elf] Error 1
arm-none-eabi-g++: error: unrecognized command-line option '--gc-sections'; did you mean '--data-sections'?
arm-none-eabi-g++: error: unrecognized command-line option '--start-group'
arm-none-eabi-g++: error: unrecognized command-line option '--end-group'
Error: Failed to build

prosv5 make VERBOSE=1:
arm-none-eabi-g++ -mcpu=cortex-a9 -mfpu=neon-fp16 -mfloat-abi=softfp -Os -g  -nostdlib -ffunction-sections -fdata-sections -fdiagnostics-color -funwind-tables -Wl,--gc-keep-exported --whole-archive firmware/libpros.a firmware/okapilib.a -lstdc++ --no-whole-archive, -Wl,-T./firmware/v5.ld --gc-sections --start-group ./firmware/libc.a ./firmware/libm.a ./firmware/libpros.a ./firmware/okapilib.a -lc -lm -lgcc -lstdc++ -lsupc++ --end-group -o bin/cold.package.elf,
Creating cold package with libc libm libpros okapilib, [ERRORS]
arm-none-eabi-g++: error: unrecognized command-line option '--whole-archive'; did you mean '--whole-file'?
arm-none-eabi-g++: error: unrecognized command-line option '--no-whole-archive,'; did you mean '--no-whole-file'?
arm-none-eabi-g++: error: unrecognized command-line option '--gc-sections'; did you mean '--data-sections'?
arm-none-eabi-g++: error: unrecognized command-line option '--start-group'
arm-none-eabi-g++: error: unrecognized command-line option '--end-group'
make: *** [common.mk:227: bin/cold.package.elf] Error 1
Error: Failed to build

**Comment by nathan-moore** [comment]
This is https://github.com/purduesigbots/pros/issues/206 . You either haven't upgraded or the upgrade didn't update common.mk. You can find the up to date version here https://github.com/purduesigbots/pros/blob/develop/common.mk .

>  saw this issue and I wonder if this is an OS issue, because that one appears to have been fixed.

In case your curious, this isn't an OS issue, but something that manifested with the latest version of make. It's just arch tends to have a very fast release cadence and tends to catch these issues. Others things usually don't, to try to avoid issues like this.
