### ISSUE TITLE
Add Tab Completion

### ISSUE THREAD

**Issue by Ian118** [purduesigbots/pros-cli#138]
I'm not sure how to write a feature request, but it would be useful to have tab-completion for the CLI, including arguments and tags.

**Comment by khuei** [comment]
@Octopus118 I wrote a rough zsh completion script for `pros-cli`. So if you are using zsh, you might be interested in using [this](https://github.com/9623X/vex-completion/blob/master/pros/zsh/_prosv5)

**Comment by kunwarsahni01** [comment]
Were going to be adding completion support through `click-completion` which will have support for fish, Zsh, Bash and PowerShell.

**Comment by khuei** [comment]
> Were going to be adding completion support through click-completion

I'm excited and looking forward to using this :smiley:
