### ISSUE TITLE
Remove links to the docs pages in the Help Messages

### ISSUE THREAD

**Issue by WillXuCodes** [purduesigbots/pros-cli#140]
With updates to the docs, these links are no longer necessary.

**Comment by WillXuCodes** [comment]
Somewhere along the line this was either done or became irrelevant as well.

**Comment by HotelCalifornia** [comment]
that's not entirely true, there dead links still present in at least the conductor commands, and possibly in other places as well

**Comment by WillXuCodes** [comment]
> that's not entirely true, there dead links still present in at least the conductor commands, and possibly in other places as well

Well I checked the link in the conductor command, and it still sends you to the conductor page (albeit with less information than it used to have), but it's still an active link that's appropriate for the command.
