### ISSUE TITLE
PROS not Identifying stdio

### ISSUE THREAD

**Issue by Anivishy** [purduesigbots/pros-cli#157]
Expected Behavior:
We expected the code to build wihtout any errors as it was working fine before we updated to the new version of pros.

Actual Behavior:
PROS failed to identify stdio, which caused the code to not be able to build/upload.

Steps to reproduce:
This error simply comes up whenever we try to use PROS. We have tried adding a path, uninstalling and reinstalling as well as repairing it but nothing has seemed to work.

System information:
Operating System:
Windos
PROS Version: 
3.2.0

Additional Information
Screenshots/Output Dumps/Stack Traces

**Comment by WillXuCodes** [comment]
Do you have a screenshot of the error? Also, the newest version of PROS is version 3.2.1 so I recommend updating. Furthermore, if you haven't updated your Kernel to 3.4.0 please do so as well.

**Comment by WillXuCodes** [comment]
Also please make a post on VEXForum or the Unofficial VEX Discord for technical help, the issues section here is for issues with the PROS code itself.
