### ISSUE TITLE
Programs getting deleted when uploading (Orphan Files)

### ISSUE THREAD

**Issue by Jchisholm204** [purduesigbots/pros-cli#158]
#### Expected Behavior:
Using prosv5 upload to upload a new program to slot one of the brain, this should upload a program to slot 1 and not interfere with any other programs on the brain

#### Actual Behavior:
Program is not uploaded the first time and programs on slot 4 and 5 are deleted from the brain

#### System information:
pros version 3.1.4
vex os version 1.0.13
windows 10

#### Screenshots/Output Dumps/Stack Traces
#CMD OUTPUT:
C:\Users\J\Documents\GitHub\1010VRepo\Master>prosv5 upload
Uploading program "Master" (hot.package.bin) to V5 slot 1 on COM9 (compressed)
Compressing library [####################################] 100%
WARNING - pros.serial.devices.vex.v5_device:upload_library - Library onboard doesn't match! Length was 588337 but expected 589377 CRC: was fd154157 but expected fd63901a
WARNING - pros.serial.devices.vex.v5_device:ensure_library_space - Removing 2 orphaned file(s) (['slot_5.bin', 'slot_4.bin'])
Uploading 1W2NmZXcf0xK76cYY633Sw [####################################] 100%
ERROR - pros.cli.upload:upload - Couldn't find the response header in the device response after 1.0 s. Got  but was expecting aa55
  File "\\wsl\Ubuntu-18.04\home\hotel\code\pros-cli\pros\serial\devices\vex\vex_device.py", line 115, in _txrx_packet
  File "\\wsl\Ubuntu-18.04\home\hotel\code\pros-cli\pros\serial\devices\vex\vex_device.py", line 75, in _rx_packet
OSError: Couldn't find the response header in the device response after 1.0 s. Got  but was expecting aa55
We detected something went wrong! Do you want to send a report? [y/N]:

**Comment by WillXuCodes** [comment]
This is its intended behavior. We deleted orphaned binaries intentionally to prevent jump table errors from happening between different versions of PROS when hot-cold linking is enabled.
