### ISSUE TITLE
  maybe "pros::ADIGyro gyro" has some bug

### ISSUE THREAD

**Issue by 3038922** [purduesigbots/pros-cli#16]
#### Expected Behavior:
get gyro value
#### Actual Behavior:
it aways return 127.0
#### System information:
Operating System:  win10 1803

PROS Version: (run `pros --version`)
pros, version 3.1.2

#### Additional Information
 in prosv5 3.1.1 ,and i use okapilib it was all right.

update prosv5 to 3.1.2 
okapilib to 3.3.5 
it was wrong
#### Screenshots/Output Dumps/Stack Traces
![image](https://user-images.githubusercontent.com/33926386/47476545-8deffa80-d853-11e8-8f57-7adfb292823a.png)
![image](https://user-images.githubusercontent.com/33926386/47476550-95af9f00-d853-11e8-9920-d85a9a730530.png)

![image](https://user-images.githubusercontent.com/33926386/47476776-89781180-d854-11e8-8788-baed6cf84b8d.png)

**Comment by HotelCalifornia** [comment]
Thanks for the report. There was in fact an issue with all the legacy sensors, which has been fixed with the release of PROS kernel 3.1.3. you can run `prosv5 conduct upgrade` in the root of your project directory to get this fix.

**Comment by 3038922** [comment]
I have updated the kernel to 3.1.3, but the master return version is still 3.1.1. Then the adi for gyro return value is still 127.
![image](https://user-images.githubusercontent.com/33926386/47539404-df0af780-d902-11e8-8b6d-af8c3a7a1a64.png)

![image](https://user-images.githubusercontent.com/33926386/47539413-e6ca9c00-d902-11e8-8999-064ed4c96071.png)
![image](https://user-images.githubusercontent.com/33926386/47539429-03ff6a80-d903-11e8-80c2-8573795dd16f.png)

**Comment by edjubuh** [comment]
See response [here](https://www.vexforum.com/index.php/35269-prosv5-the-problem-of-setting-the-gyroscope-to-a-global-class/p1#p285857).
