### ISSUE TITLE
Bug report sending defaults to "no"

### ISSUE THREAD

**Issue by iuyte** [purduesigbots/pros-cli#17]
#### ~~Expected~~ *Desired* Behavior:
`Would you like to send a bug report to the PROS Development team? [Y/n]: ` defaults to "no"
#### Actual Behavior:
It defaults to "yes"
#### Steps to reproduce:
run anything that isn't right, like trying to upload without compiling first
#### System information:
Operating System: Fedora 28 Stable
PROS Version: 3.1.0
#### Additional Information
If you disagree just close this, thanks

**Comment by edjubuh** [comment]
When I decided to make it default yes, my philosophy was that I figured users who mash the enter button would end up sending us bug reports. I'd rather see a bug report when something goes wrong than not, even if it's not a real bug (e.g. you don't have permissions on the USB port or you mistyped some command). If you realize that the bug report prompt wasn't necessary, then you should actively realize it and say "no."

I'm fine with it defaulting to no if there's additional positive user feedback to change the default.

**Comment by iuyte** [comment]
Maybe an option to change the default response, or a `-n`/`--no` for commands to default to `no`
