### ISSUE TITLE
Initialization Error

### ISSUE THREAD

**Issue by ProJeth** [purduesigbots/pros-cli#170]
Hello. I am getting an error of pros::motor not being matched as a constructor. I would like some help to fix this, please. It would be appreciated if you could give me the steps exactly how to fix it. Thanks.

**Comment by HotelCalifornia** [comment]
the first step is posting the erroneous code so we can see what's going on

**Comment by WillXuCodes** [comment]
Closing this due to how this is irrelevant to code issues with the CLI. Please post your question on vexforum.com or other support channels instead.
