### ISSUE TITLE
"-nostartfiles" flag no longer accepted in newest version of compiler. requires "--nostartfiles"

### ISSUE THREAD

**Issue by jergao** [purduesigbots/pros-cli#176]
#### Expected Behavior:
Normal compilation of project.

#### Actual Behavior:
Error when linking. 
`Linking hot project with ./bin/cold.package.elf and libc,libm,libpros,okapilib [ERRORS]
/home/username/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: Error: unable to disambiguate: -nostartfiles (did you mean --nostartfiles ?)`
This can be related to [this change in gcc](https://githubmemory.com/repo/linux4sam/at91bootstrap/issues/127).

#### Steps to reproduce:
Attempt to compile a project in linux using newest compiler from the [ARM website](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads).

#### System information:
Operating System:  Ubuntu 21.10

PROS Version: pros, version 3.2.2

#### Additional Information
Compiler: `gcc-arm-none-eabi-10.3-2021.10`

#### Screenshots/Output Dumps/Stack Traces
Output:
`username@Computer:~/Desktop/#80/VEX/CROS$ pros make
Adding timestamp [OK]
Linking hot project with ./bin/cold.package.elf and libc,libm,libpros,okapilib [ERRORS]
/home/username/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: Error: unable to disambiguate: -nostartfiles (did you mean --nostartfiles ?)
collect2: error: ld returned 1 exit status
make: *** [common.mk:239: bin/hot.package.elf] Error 1
ERROR - pros.cli.build:make - Failed to make project: Exit Code 2
Error: Failed to build
`

**Comment by WillXuCodes** [comment]
This was a Kernel end issue, and will be fixed in the next release (3.5.3). For now, you can change line 239 in common.mk to:
`
$(call test_output_2,Linking hot project with $(COLD_ELF) and $(ARCHIVE_TEXT_LIST) ,$(LD) -nostartfiles $(LDFLAGS) $(call wlprefix,-R $<) $(filter-out $<,$^) $(LDTIMEOBJ) $(LIBRARIES) $(call wlprefix,-T$(FWDIR)/v5-hot.ld $(LNK_FLAGS) -o $@),$(OK_STRING))`
