### ISSUE TITLE
Display version number when an error occurs

### ISSUE THREAD

**Issue by cgjeffries** [purduesigbots/pros-cli#187]
To aid in troubleshooting for both the user and those assisting them it would be useful for the CLI to print its own version number when an unrecoverable error is reached, such as when uploading fails. This way it would be simple for everyone involved to see what version of the CLI is in use.

Secondarily, when a compile error occurs it could be useful for the CLI to print the version number of the kernel in use in the project, for similar reasons as above.

**Comment by omegaStag** [comment]
Closed by #237
