### ISSUE TITLE
Linker script syntax error

### ISSUE THREAD

**Issue by mattfbacon** [purduesigbots/pros-cli#217]
OS: Arch Linux
PROS version: 3.6.0

When running `prosv5 make` and/or `make`:

```
Creating cold package with libc,libm,libpros,okapilib [ERRORS]
/usr/lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld:./firmware/v5-common.ld:30: syntax error
collect2: error: ld returned 1 exit status
make: *** [common.mk:229: bin/cold.package.elf] Error 1
```

The syntax looks fine to me. Not sure what's tripping up the linker here.

**Comment by HotelCalifornia** [comment]
uhm.. interesting. does this happen for arm-none-eabi 10 or 11?

**Comment by mattfbacon** [comment]
Sorry, I just realized I put this on the pros-cli repo rather than pros itself. I'll move it.
