### ISSUE TITLE
Docstrings out of date

### ISSUE THREAD

**Issue by Bottersnike** [purduesigbots/pros-cli#22]
The initial docstring I found that was out of date was https://github.com/purduesigbots/pros-cli3/blob/master/pros/serial/devices/vex/v5_device.py#L406, however I suspect there might be a few others dotted around the place that have likewise dropped out of date as code has changed over time (hence the vague issue title).

**Comment by HotelCalifornia** [comment]
> `prosv5 c --help` directs users to this link which is broken:
`<https://pros.cs.purdue.edu/v5/cli/conductor>`

**Comment by edjubuh** [comment]
I'm not sure what the reported issue is, so closing for now until that's clear.
