### ISSUE TITLE
PROS-CLI 4: Upgrade Click

### ISSUE THREAD

**Issue by omegaStag** [purduesigbots/pros-cli#227]
The CLI uses Click major version 6.7, and the most recent version of Click is on major version 8. In order to upgrade to Click's most recent version, we need to do a rewrite of a lot of the CLI, hence, PROS-CLI 4. [Documentation for Click is here.](https://click.palletsprojects.com/en/8.1.x/) Once this is done, we can add things like tab completion to the CLI. New branch [develop-pros-cli-4](https://github.com/purduesigbots/pros-cli/tree/develop-pros-cli-4) has been created for this purpose.

Version 6 to 7, more improvements/auto complete
7 to 8, most breaking changes here - how commands are grouped

**Comment by omegaStag** [comment]
Add tab completion: https://github.com/purduesigbots/pros-cli/issues/138

**Comment by mayankpatibandla** [comment]
@ayushuk We upgraded to Click 8 in #307 can we close this?

**Comment by ayushuk** [comment]
Closing because this was done in, #138 is still a TODO.
