### ISSUE TITLE
If field control is used, the robot has a probability of operating delay.

### ISSUE THREAD

**Issue by 3038922** [purduesigbots/pros-cli#23]
Expected Behavior:
Complete a match normally.
Actual Behavior:
1 I confirm that my field control program is up to date.
If field control is used, the robot has a probability of operating delay.
The same problem occurs when the field control is not connected, but the probability decreases.
Maybe I use NEW's relational system and occasionally it's not fully initialized. I'll add pros:: delay (100) to my test tomorrow.
I've tried to get sensor values in the class, and if you don't add pros:: delay (100), the values you get are wrong.
Steps to reproduce:
System information:
Operating System: (Windows, OS X, Ubuntu)
windows 10 1807
PROS Version: (run pros --version)
pros, version 3.1.2

Additional Information
kernel 3.3.4
oklib 3.3.7

Screenshots/Output Dumps/Stack Traces
![image](https://user-images.githubusercontent.com/33926386/48970811-c69a1400-f04b-11e8-97bd-643b53b70eff.png)

![image](https://user-images.githubusercontent.com/33926386/48970869-c8b0a280-f04c-11e8-9fbe-fae4a30fc633.png)

**Comment by HotelCalifornia** [comment]
so you're saying that trying to use sensor values in a C++ constructor gives wrong values for the first ~100ms?

Where are you creating an instance of `Intake`? If it's in a global scope, then this is expected, as global C++ constructors are called before most things have finished initializing.

also: using `new` shouldn't have any appreciable effect on your program's runtime performance.

**Comment by 3038922** [comment]
Sorry,My student's judgment should be VEX OS problem. only one robot never goes wrong.This delay problem occurs when more than four V5 robots start at the same time.

**Comment by HotelCalifornia** [comment]
in that case, I'm going to close this issue as it doesn't seem to be PROS-specific.
