### ISSUE TITLE
🐛Workflows never finish

### ISSUE THREAD

**Issue by liam-teale** [purduesigbots/pros-cli#232]
#### Expected Behavior:
For the workflows to stop after a few minutes.

#### Actual Behavior:
The workflow gets stuck when building for macOS ARM

#### Steps to reproduce:
Commit and push to the repo

#### Additional Information
GitHub workflow time is billed (IIRC). It could cost a lot of money letting it run like this

#### Screenshots/Output Dumps/Stack Traces
![image](https://user-images.githubusercontent.com/111480281/192877783-d1cd60b1-77f6-4ddd-8905-ba201bf4e03e.png)

**Comment by omegaStag** [comment]
Good catch, @kunwarsahni01 pls help

**Comment by kunwarsahni01** [comment]
Ah, a couple things here, we actually use Azure Pipelines not github workflows (Azure is free for us no matter what), we also have a built in timeout in all pipelines so no pipeline will be running for more than 15 minutes. And in this case it was just a case of the M1 in the cloud we are running getting turned off, so restarted it and it should be all good.
