### ISSUE TITLE
✨Make Clean when Removing a Template

### ISSUE THREAD

**Issue by sy1vi3** [purduesigbots/pros-cli#234]
#### Requested Feature
Automatically run `make clean` when removing a template using `pros c uninstall`.

#### Is this Feature Related to a Problem?
I was struggling to figure out why a library that I had removed was still doing stuff after I had removed it, recompiled, and redownloaded the program. 

#### Benefits of Feature
So people don't get confused about why their code is doing things they aren't telling it to do.

**Comment by ayushuk** [comment]
Closed by #244
