### ISSUE TITLE
There are some problems. about cquery and compile_commands.json

### ISSUE THREAD

**Issue by 3038922** [purduesigbots/pros-cli#24]
![image](https://user-images.githubusercontent.com/33926386/49021780-5d8ed980-f1ce-11e8-848d-4e1b75e76875.png)
There are already some answers to this question.

https://github.com/cquery-project/cquery/issues/506

https://gitlab.kitware.com/cmake/cmake/issues/17482

**Comment by HotelCalifornia** [comment]
I'm going to close this as it doesn't seem to be a PROS-specific issue... if I were to make a guess though, I'd say it's having trouble with non-ASCII paths or something.
