### ISSUE TITLE
✨PROS 4 Upgrade Prompt

### ISSUE THREAD

**Issue by omegaStag** [purduesigbots/pros-cli#241]
#### Requested Feature
When the user wants to upgrade their project to PROS 4, they should be warned that it will cause breaking changes and that they will have to change their codebase accordingly.

#### Is this Feature Related to a Problem?
This feature is related to PROS 4.

#### Benefits of Feature
Make sure that people don't upgrade their projects without being aware of the consequences.

#### Additional Information
This should be a fairly simple check if the kernel template to be applied to an existing project is major version 4.

**Comment by ayushuk** [comment]
Completed in #296
