### ISSUE TITLE
Can you give me a copy of CMakeLists. txt?

### ISSUE THREAD

**Issue by 3038922** [purduesigbots/pros-cli#27]
Atom is difficult to install plug-ins in China,I built my own cquery server on vscode, but it always seems to be a problem. I want to see the original "CMakeLists. txt" file in order to identify the problem.

**Comment by HotelCalifornia** [comment]
Anything related to cquery can be found in its repository here: [cquery-project/cquery](https://github.com/cquery-project/cquery)
