### ISSUE TITLE
Feature Request: V5 Vision Utility Equivalent for Linux

### ISSUE THREAD

**Issue by breqdev** [purduesigbots/pros-cli#30]
The PROS documentation states that the only way to use the vision sensor with PROS is to first set color signatures in Vex Coding Studio. However, this software is not available for Linux, so I have no way of using the vision sensor on my laptop. Is this something you could potentially support with pros-cli? If not, do you know of another program I could use to create color signatures that would run on Linux?

**Comment by HotelCalifornia** [comment]
Until VEX releases a version of the Vision Utility for Linux, there's not much we can do. It's not something we can support from the CLI, in any case.

Running Windows in a VM may be a good workaround.
