### ISSUE TITLE
How to turn off GCC, a note type prompt?

### ISSUE THREAD

**Issue by 3038922** [purduesigbots/pros-cli#31]
![image](https://user-images.githubusercontent.com/33926386/50195730-4e3d1f00-037b-11e9-9914-963df3d0e9e5.png)
Or how can I assign a value to  valarray<T> type?
![image](https://user-images.githubusercontent.com/33926386/50195756-66ad3980-037b-11e9-8461-a409dde40223.png)

**Comment by HotelCalifornia** [comment]
This is not an issue with PROS, but rather with C++ and GCC.

**Comment by HotelCalifornia** [comment]
You can solve this [by adding `-Wno-psabi`](https://stackoverflow.com/a/48149400) to the `WARNFLAGS` variable in your Makefile

**Comment by 3038922** [comment]
Thank you.  hope you will add this option by default in future versions.
