### ISSUE TITLE
can not upload to v5 brain in macbook

### ISSUE THREAD

**Issue by pieceofpie** [purduesigbots/pros-cli#34]
#### System information:
Operating System:  (Windows, OS X, Ubuntu)
MacBookPro
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro10,1
  Processor Name:	Intel Core i7
  Processor Speed:	2.7 GHz
macOS 10.13.6

PROS Version: (run `pros --version`)
pros, version 3.1.3

prosv5 v5 status
Connected to V5 on /dev/cu.usbmodem1421
System version: 1.0.5-0
CPU0 F/W version: 1.0.0-27
CPU1 SDK version: 1.0.4-3

#### Screenshots/Output Dumps/Stack Traces
$ prosv5 upload --slot 5
Uploading /Users/BitTorrent Sync/test/bin/output.bin to v5 device on /dev/cu.usbmodem1421 as test to slot 5
Uploading slot_5.ini [####################################] 100%
Uploading slot_5.bin (/Users/BitTorrent Sync/test/bin/output.bin) [------------------------------------]   1% 0d 00:01:49
ERROR - pros.cli.upload:upload - Couldn't find the response header in the device response. Got  but was expecting aa55
  File "/usr/local/Cellar/pros-cli/3.1.3/libexec/lib/python3.7/site-packages/pros/serial/devices/vex/vex_device.py", line 69, in _rx_packet
    raise IOError(f"Couldn't find the response header in the device response. "
OSError: Couldn't find the response header in the device response. Got  but was expecting aa55
We detected something went wrong! Would you like to send a bug report to the PROS Development team? [Y/n]:

**Comment by HotelCalifornia** [comment]
Closing this as a duplicate of #9. I only closed it due to a lack of activity. Reopening now
