### ISSUE TITLE
cannot create project after installation

### ISSUE THREAD

**Issue by ghost** [purduesigbots/pros-cli#37]
#### Expected Behavior:
create a project
#### Actual Behavior:
errors creating the project with a return of `A project already exists in this location! Delete it first`
#### Steps to reproduce:
open the editor and click create a project
#### System information:
Operating System:  (Windows, OS X, Ubuntu)
OS X Mojave
PROS Version: (run `pros --version`)
3.1.3
#### Additional Information
The creation of a new project succeeded only once and took a long time to complete.
#### Screenshots/Output Dumps/Stack Traces
![screen shot 2019-01-19 at 15 15 53](https://user-images.githubusercontent.com/30623403/51423556-200e6180-1bfd-11e9-937e-6df9b25482ac.png)

**Comment by ghost** [comment]
I tried several other directories with no files in them and none of them worked.

**Comment by edjubuh** [comment]
After creating a project that fails, can you open the console and share any messages that were generated from you creating a new project? 

You can open the console by opening the command palette (Cmd+Shift+P I think on OS X) and searching for "Console: Toggle".

**Comment by ghost** [comment]
The problem is solved. The cause was that I once carelessly created a project in the root directory in which almost all my files are stored(~/) and therefore new projects cannot be created in the subdirectories whose parent directory already contains a `project.pros`.

The directory diagram looks like this:

.
└── root
    ├── TheProjToBeCreatedIn
           └── WhereCreationFailed
    ├── makefilesAnd.etc
    ├── mydir1
    ├── mydir2
    ├── mydir3
    └── project.pros

When trying to create a project this way, pros CLI assumes that you are trying to create a project within one of the resources folders in a project already created. Such a fool I was.......`:(`

Apparently, this is a careless mistake of mine instead of a bug. But I suggest that It's good to add a confirmation message to the notification panel shown above that asks: `Are you trying to create a project in a project?`, so that users will get awared of the situation.

**Comment by edjubuh** [comment]
Thanks for figuring this out. I've opened an issue to give a better error message.
