### ISSUE TITLE
Add ability to change program icon on v5 brain

### ISSUE THREAD

**Issue by brynn-ray** [purduesigbots/pros-cli#41]
**Desired Feature:**
Custom image for program on robot's brain

**Comment by Bottersnike** [comment]
I may be wrong, but I believe these icons are hardcoded into VEXos and thus would require changes in the device firmware to allow for non-standard icons?

**Comment by edjubuh** [comment]
As @Bottersnike mentioned, program icons are part of the assets package included in vexOS - they're not currently user-customizable. There are some user program icons included, but I'm not sure what they are. If someone is willing to experiment to figure out what icons exist and the relevant filenames, I'll add a feature to let you change it.

Relevant line:
https://github.com/purduesigbots/pros-cli/blob/80684a1d835a474f19bc417d4842f32b90a8b8ca/pros/serial/devices/vex/v5_device.py#L101

**Comment by HotelCalifornia** [comment]
I think the original ask was actually less about arbitrary icons and more about letting users select from the ones that are built-in (à la VCS)

**Comment by Bottersnike** [comment]
If I remember correctly, the icons go from USER901x to USER905x, but there might be others I didn't find when I went hunting a while back.

**Comment by Nenik** [comment]
I've got pizza slice for USER003x at some point :-)

**Comment by Ian118** [comment]
A list of icons available: https://www.vexforum.com/t/a-guide-to-changing-program-icons/78293/7

**Comment by kunwarsahni01** [comment]
Now added in #194
