### ISSUE TITLE
Validate new projects are not in users' home folders

### ISSUE THREAD

**Issue by Octogonapus** [purduesigbots/pros-cli#65]
#### Expected Behavior:
When making a new project, some users click through the menu without creating a new folder for their project, which results in their home folder being used. These users then encounter #44. I would prefer that the editor not allow users to make projects in their home folders (i.e. validate the selected folder is not `C:\Users\Salmon`, etc.).

#### Actual Behavior:
Users can make a project in their home folder.

#### Steps to reproduce:
1. Start making a new project
2. Accept the default project location (typically `C:\Users\Salmon` or equivalent)

**Comment by edjubuh** [comment]
With interactive UI, the default location will be C:\Users\Salmon\My PROS Project or the directory of whatever file you have open. But we should also still explicitly forbid this behavior since I've never seen it do anyone good.
