### ISSUE TITLE
Unable to run make

### ISSUE THREAD

**Issue by pieceofpie** [purduesigbots/pros-cli#79]
#### Expected Behavior:

the command would not run after installed the new version of pros 3.1.4.0.

#### Actual Behavior:

cannot find the files specified. See the attached picture for detail.

E:\D\Resilio Sync\mic\robotics\pmg\VEX2018\test>prosv5 make
ERROR - __main__:main - [WinError 2] The system cannot find the file specified
  File "C:\hostedtoolcache\windows\Python\3.6.4\x64\lib\subprocess.py", line 709, in __init__
  File "C:\hostedtoolcache\windows\Python\3.6.4\x64\lib\subprocess.py", line 997, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

#### System information:
Operating System:  
OS Version:	Windows 10
OS_Architecture:	64-bit
Service Pack:	No service pack
CPU:	Quad 3.70 GHz Intel Xeon(R)E3-1240 v6 (Hyper-Threaded)
Memory:	32700 MB
Manufacturer:	Dell Inc.
Model:	Precision Tower 3620
Service Tag:	6F101S2

PROS Version: 
pros 3.1.4.0

#### Screenshots/Output Dumps/Stack Traces
![screen-2019-02-22_09-03-14](https://user-images.githubusercontent.com/45878445/53250994-3aff4600-3681-11e9-8839-cf84f15a7c83.jpg)

**Comment by edjubuh** [comment]
Do you have the PROS_TOOLCHAIN environment variable set? The installers should do this, but sometimes they don't on some machines.

**Comment by pieceofpie** [comment]
C:\Users\xyz>echo %PROS_TOOLCHAIN%
C:\Users\xyz\AppData\Local\Programs\PROS\toolchain\

find subprocess.py in C:\Users\xyz\AppData\Local\Programs\Python\Python37-32\Lib\

**Comment by pieceofpie** [comment]
solve the issue after uninstall and manually remove the residual files. reinstall PROS and everything seems fine
