### ISSUE TITLE
Conductor upgrade produces the wrong error message

### ISSUE THREAD

**Issue by Octogonapus** [purduesigbots/pros-cli#8]
#### Expected Behavior:

When I run `prosv5 c u` in a project where everything is up to date, I expect to see something like
```
kernel@3.1.0 is up-to-date.
okapilib@3.2.0 is up-to-date.
```

#### Actual Behavior:

At the least, the current error is wrong. `Upgrading is allowed` isn't allowed if it gives me an error! :)

```
Upgrading kernel
WARNING - pros.conductor.conductor:apply_template - Could not install kernel@3.1.0 because it is not new to the project. Upgrading is allowed, and installing is not allowed
Upgrading okapilib
WARNING - pros.conductor.conductor:apply_template - Could not install okapilib@3.2.0 because it is not new to the project. Upgrading is allowed, and installing is not allowed
```

#### Steps to reproduce:

Run `prosv5 c u` in a project that's up to date.

#### System information:
Operating System:  (Windows, OS X, Ubuntu)
Ubuntu 18.04

PROS Version: (run `pros --version`)
3.1.0

**Comment by HotelCalifornia** [comment]
closed in #38

**Comment by HotelCalifornia** [comment]
not closed yet, oops

**Comment by edjubuh** [comment]
Error message now looks like:
```
pros.conductor.project.template_resolution.InvalidTemplateException: Could not install kernel@3.1.6 because it is AlreadyInstalled, and that is not allowed.
```

**Comment by Octogonapus** [comment]
I would much rather get a message like, "kernel@3.1.6 is already installed.". Exceptions are scary.
