### ISSUE TITLE
Pros 3.1.4.0 Windows msi installer broken

### ISSUE THREAD

**Issue by Samuel12321** [purduesigbots/pros-cli#87]
#### Expected Behavior:
Installer to work correctly

#### Actual Behavior:
Boxes all whited out and the accept ansd install button doesnt work
#### Steps to reproduce:
Download and run pros 3.1.4.0 msi installer

#### System information:
Operating System:  
Windows 10 1803 32bit
windows 10 1809 64bit
Windows 10 1903(beta ) 64bit 
windows 10 1511 32bit

PROS Version: 
![annotation 2019-03-08 212525](https://user-images.githubusercontent.com/35312698/54016805-f7601c80-41e8-11e9-8070-d89b36bbd796.jpg)
![annotation 2019-03-08 212504](https://user-images.githubusercontent.com/35312698/54016806-f7f8b300-41e8-11e9-9600-a6a494952d91.jpg)
![annotation 2019-03-08 212447](https://user-images.githubusercontent.com/35312698/54016808-f7f8b300-41e8-11e9-992e-cde8571ae5c1.jpg)

#### Additional Information

has been tried on 4 different windows 10 computers and has the same outcome

**Comment by edjubuh** [comment]
The MSI is intended for network deployments of PROS. You should use the appropriate EXE-based installer
