### ISSUE TITLE
latest Pros 3.1.4.0 32bit exe installs old cortex pros

### ISSUE THREAD

**Issue by Samuel12321** [purduesigbots/pros-cli#88]
#### System information:
Operating System:  
windows 10 1803 32bit
sorry will add more info soon

**Comment by HotelCalifornia** [comment]
any more info?

**Comment by Samuel12321** [comment]
Seems to install the pros 0.75 package and bootstrapper

**Comment by Samuel12321** [comment]
This causes an error stating it cant find the pros cli on path,
possibly due to having the pros cli 3 and the pros 0.75 packages

**Comment by Samuel12321** [comment]
Will try to test again on another 32bit laptop running windows 7. Is there anything you want me to do to make the test more usefull?

**Comment by kunwarsahni01** [comment]
We have now removed all 32-bit installers so this is no longer applicable.

**Comment by HotelCalifornia** [comment]
you may still use the CLI directly on 32-bit machines by extracting the standalone CLI release (e.g. pros_cli-3.2.1-win-32bit.zip), however you will not get the full PROS Editor experience (and we will likely not be able to help if there are any problems)
