### ISSUE TITLE
Feature request for terminal over wireless

### ISSUE THREAD

**Issue by Sleuth56** [purduesigbots/pros-cli#94]
#### Expected Behavior:
When plugged into the V5 controller to be able to run prosv5 terminal and see the terminal output of the brain.

#### Actual Behavior:
Gives an error that you need to plug in to the brain.

#### Steps to reproduce:
1. Plug in to a V5 controller paired to a V5 brain.
2. Run a program that has terminal output via printf.
3. open a terminal on your computer and run prosv5 terminal.

#### System information:
Platform:V5
PROS Kernel Version: 3.1.6

**Comment by edjubuh** [comment]
What's the output of `prosv5 lsusb --debug`?

**Comment by Sleuth56** [comment]
I don't have a brain to test with until tomorrow but it was connected because a could upload over the connection

**Comment by edjubuh** [comment]
If you're connected via joystick, we don't support user terminal over the joystick yet.

**Comment by Sleuth56** [comment]
That's why I labeled it as a feature request. It would be a nice to have for debugging.

**Comment by edjubuh** [comment]
Oh pff, totally didn't read the title or the first phrase of the issue.

**Comment by Sleuth56** [comment]
Is there a better place for feature requests?

**Comment by HotelCalifornia** [comment]
No, here is fine

**Comment by Sleuth56** [comment]
Any luck with the vision sensor? I was told back in February that you all hadn't gotten it to work yet.

**Comment by HotelCalifornia** [comment]
I'm not sure what you mean, but let's stay on topic here

**Comment by HotelCalifornia** [comment]
This feature hasn't landed yet, not sure why we're closing it

**Comment by Sleuth56** [comment]
The PR said that it had been merged. I figured that GitHub just didn't close this issue for some reason.
