### ISSUE TITLE
BSS become bigger when you upgrade your kernel to 3.1.6

### ISSUE THREAD

**Issue by Jerrylum** [purduesigbots/pros-cli#95]
The BBS file is too big and slow down the upload time. The output file is very small when you are using kernel@3.1.4 but it is very large when you are upgrade/in 3.1.6

> Update:
> It won't slow down the upload time. When you enable hot/cold function and upload, CLI need to upload the library ❄️  and project code 🔥   in the first time. It need to upload two file and it is very slow. Ever slower than disabled or using an older CLI. I thought it was kernel problem.
> ![image](https://user-images.githubusercontent.com/12783829/57768719-d19e4900-773e-11e9-93d0-90604ae2b096.png)

#### Steps to reproduce:
1. make a folder call prosv5-sandbox3
2. open a new console on there
3. use command `prosv5 c n .`
4. Because of auto compile, you can see the result of section size, it is about 48MB (Using kernel@3.1.6)
![image](https://user-images.githubusercontent.com/12783829/57760072-90516d80-772d-11e9-9f49-1c8aaa86cd2a.png)

5. copy `common.mk`, `compile_commands.json` and `Makefile` to a folder call "backup"
6. use command `prosv5 c upgrade kernel@3.1.4`
7. paste the file from `backup` folder to `prosv5-sandbox3`
8. use command `prosv5 make all` and you can see it is only 3MB
![image](https://user-images.githubusercontent.com/12783829/57760048-8465ab80-772d-11e9-9a32-0d0e2950137b.png)

#### System information:
Operating System:  Windows

PROS Version: 3.1.6

#### Additional Information
It may not a problem of pros-cli because I try to reproduce the issue on cli@3.1.2 and it has the same result.
It is also not a problem of the project config files(like common.mk etc).

I try to use git to track which files changed and there it is:
![image](https://user-images.githubusercontent.com/12783829/57760602-82501c80-772e-11e9-9db4-7f2814367ee3.png)

**Comment by HotelCalifornia** [comment]
https://en.wikipedia.org/wiki/.bss

**Comment by Jerrylum** [comment]
I know BSS doesn't take up any actual space in the object file now and it won't slow down the upload time, but I still want to know why it is very big. What's the difference between two version?

**Comment by edjubuh** [comment]
> I know BSS doesn't take up any actual space in the object file now and it won't slow down the upload time, but I still want to know why it is very big. What's the difference between two version?

We increased heap size from 1MB to 48MB
https://github.com/purduesigbots/pros/commit/728dcb1a4f8bb693bf3b71d6d0369033bad848ab#diff-3e67e7437ae7de6cc9138170266edcdaR1
https://github.com/purduesigbots/pros/commit/728dcb1a4f8bb693bf3b71d6d0369033bad848ab#diff-4bf621f08c857fdd0610fb8794f275e2L17
