### ISSUE TITLE
Unable to upload without PROS project

### ISSUE THREAD

**Issue by lights0123** [purduesigbots/pros-cli#96]
#### Expected Behavior:
As per the help in `prosv5 upload --help`:

>   [PATH] may be a directory or file. If a directory, finds a PROS project root and uploads the binary for the correct target automatically. **If a file, then the file is uploaded**. Note that --target must be specified in this case.

Attempting to upload a file using `prosv5 upload --target v5 path/to/binary.bin` without a PROS project should work.
#### Actual Behavior:
The following error message is given:
```
❱ prosv5 upload --target v5 path/to/binary.bin
Usage: pros upload [OPTIONS] [PATH] [PORT]

Error: «current directory» is not inside a PROS project. Execute this command from within a PROS project or specify it with --project project/path
```

#### Steps to reproduce:
1. Go to a directory that does not have a `project.pros` file, and have a V5 system connected
2. Place a valid binary in an accessible path, e.g. with `objcopy -O binary -R .hot_init` or copying from a PROS project
3. Attempt to upload a file with `prosv5 upload --target v5 path/to/binary.bin`

#### System information:
Operating System:  Antergos Linux

PROS Version: `pros, version 3.1.4`

**Comment by HotelCalifornia** [comment]
Yeah I'm pretty sure the problem is that V5 uploads also require the .ini file, and I'm not sure that gets generated automatically when specifying a file

**Comment by HotelCalifornia** [comment]
Which is by design-- we can't really guess values for the content without project info. 

(I'm assuming here that you're trying to upload a binary that will be run as user code, which is what the `prosv5 u` command is for)

**Comment by HotelCalifornia** [comment]
@lights0123 you were trying to upload a binary to be run as user code, right?

I think the best we can do here is to add logic that won't accept a file when the target is v5 and some to be determined set of the v5 options flags are left unspecified.

**Comment by lights0123** [comment]
@HotelCalifornia correct—I was trying to upload code not created by PROS, and just using the PROS CLI as a tool to upload the binary. I ended up just writing a script to copy the binary into a PROS project and then uploading it. However, it would be useful to be able to skip all of that and upload it directly with command line arguments.

**Comment by HotelCalifornia** [comment]
In the meantime, you can work around this issue by creating a dummy project.pros file in your project directory, then specifying the path to the binary.
